### ISSUE TITLE
Built-in browser

### ISSUE THREAD

**Issue by DutchPete** [mirnovov/elf#1]
> You can either obtain the plugin using Obsidian's built-in browser

How does that work? Please explain because I would like to try your plug-in.

**Comment by wenlzhang** [comment]
The following plugin might be of interest of testing beta plugins:
https://github.com/TfTHacker/obsidian42-brat

**Comment by mirnovov** [comment]
I mean Obsidian’s built-in facility for installing community plugins. Unfortunately, that’s not available yet as the plug-in needs to be approved first. I’d second wenlzhang’s advice to use BRAT, as it’s much easier than manually installing the plugin.
