### ISSUE TITLE
Reading button doesn't appear

### ISSUE THREAD

**Issue by Mara-Li** [mirnovov/elf#4]
The view toggle is hided, but I have disabled the option to hide it.
![image](https://user-images.githubusercontent.com/30244939/150492152-d7a18d57-a0b8-4d6e-bf18-153d29800326.png)
![image](https://user-images.githubusercontent.com/30244939/150492170-25034124-926f-4eed-96c3-0d59de23b1ee.png)

**Comment by mirnovov** [comment]
I forgot to add the change that actually makes the button work to the commit, sorry. I've redone the commit with the change; it should now work.
